# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"
ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'

# Start config
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # Turn off shared folders
  config.vm.synced_folder "./", "/vagrant", disabled: true

  # Define instance - devstack all-in-one devstack box configuration
  config.vm.define "devstack" do |devstack_config|

    # Provide box name, download url, etc.
    devstack_config.vm.hostname = "devstack"
    devstack_config.vm.box = "base"
    devstack_config.vm.box_url = "https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box"

    # Execute shell script within the new vm after it boots
    devstack_config.vm.provision "shell", path: "vagrant-post.sh"

    # Configure networking
    # eth0 - Default route / NAT, auto-configured and required by Virtual Box
    # eth1 - API / management network
    devstack_config.vm.network "private_network", ip: "192.168.1.129"
    # eth2 - Neutron / bridge network
    devstack_config.vm.network "private_network", ip: "192.168.2.129"
    # eth3 - Public network (bridged adapter config if needed)
    # devstack_config.vm.network "public_network", :adapter => 4 , type: "dhcp", :bridge => 'en0: Wi-Fi (AirPort)'

    # Define extra vm options
    devstack_config.vm.provider "virtualbox" do |vb|
        # Don't boot in headless mode
        vb.gui = true
        # Set CPU and RAM
        vb.customize ["modifyvm", :id, "--memory", "4096"]
        vb.customize ["modifyvm", :id, "--cpus", "2"]
        # Enable promiscuous mode on neutron nic
        vb.customize ["modifyvm", :id, "--nicpromisc3", "allow-all"]
        # Enable VT pass through
        vb.customize ["modifyvm", :id, "--hwvirtex", "on"]
    end

  end

end
