#!/bin/bash
# Set verbose
set -v

# Set exit on error
set -e

# Set passwords
echo root:stack | chpasswd

# Populate hosts file
cat << EOF >> /etc/hosts

172.16.0.10 ubuntu1404
172.16.0.11 xubuntu1404
EOF

# Configure network interfaces
cat << EOF > /tmp/interfaces
# This file describes the network interfaces available on your system
# and how to activate them. For more information, see interfaces(5).

# The loopback network interface
auto lo
iface lo inet loopback

# The primary network interface
# Adapter 1, NAT, default route
auto eth0
iface eth0 inet dhcp
pre-up sleep 2

# The contents below are automatically generated by Vagrant. Do not modify.
# API / host management network
auto eth1
iface eth1 inet static
      address 172.16.1.10
      netmask 255.255.255.0

# The contents below are automatically generated by Vagrant. Do not modify.
# Neutron provider network
auto eth2
iface eth2 inet manual
      up ifconfig $IFACE 0.0.0.0 up
      down ifconfig $IFACE 0.0.0.0 down

# The contents below are automatically generated by Vagrant. Do not modify.
auto eth3
iface eth3 inet dhcp
    post-up route del default dev $IFACE || true
EOF

cp -f /tmp/interfaces /etc/network/interfaces

# Speedup boot time
sed -i -e 's/sleep/# sleep/g' /etc/init/failsafe.conf

# Install Virtual Box guest additions
apt-get -y install linux-headers-generic build-essential dkms
wget http://dlc-cdn.sun.com/virtualbox/4.3.26/VBoxGuestAdditions_4.3.26.iso
mkdir /media/VBoxGuestAdditions
mount -o loop,ro VBoxGuestAdditions_4.3.26.iso /media/VBoxGuestAdditions
sh -c "/media/VBoxGuestAdditions/VBoxLinuxAdditions.run --nox11" >> /dev/null 2>&1
rm -rf VBoxGuestAdditions_4.3.26.iso
umount /media/VBoxGuestAdditions
rmdir /media/VBoxGuestAdditions

# Reboot
reboot
