heat_template_version: 2014-10-16  
parameters:
  key_name:
    type: string
    default: my-key
  node_name:
    type: string
    default: lb-vm
  node_server_flavor:
    type: string
    default: m1.small
  node_image_name:
    type: string
    default: cirros-0.3.4-x86_64-uec
  floating_net_id:
    type: string
  private_net_id:
    type: string
  private_subnet_id:
    type: string
  pool_id:
    type: string
  initial_capacity:
    type: number
    default: 1
  cooldown_policy_seconds:
    type: number
    default: 30
  asg_group_min_size:
    type: number
    default: 1
  asg_group_max_size:
    type: number
    default: 3

resources:
  web_scaler:
    type: OS::Heat::AutoScalingGroup
    properties:
      desired_capacity: {get_param: initial_capacity}
      cooldown: {get_param: cooldown_policy_seconds}
      max_size: {get_param: asg_group_max_size}
      min_size: {get_param: asg_group_min_size}
      resource:
        type: OS::Nova::Server::Scaled
        properties:
          node_server_flavor: {get_param: node_server_flavor}
          node_image_name: {get_param: node_image_name}
          key_name: {get_param: key_name}
          floating_net_id: {get_param: floating_net_id}
          private_net_id: {get_param: private_net_id}
          private_subnet_id: {get_param: private_subnet_id}
          pool_id: {get_param: pool_id}

  scaleup_policy:
    type: OS::Heat::ScalingPolicy
    properties:
      adjustment_type: change_in_capacity
      auto_scaling_group_id: { get_resource: web_scaler }
      cooldown: {get_param: cooldown_policy_seconds}
      scaling_adjustment: 1

  scaledown_policy:
    type: OS::Heat::ScalingPolicy
    properties:
      adjustment_type: change_in_capacity
      auto_scaling_group_id: { get_resource: web_scaler }
      cooldown: {get_param: cooldown_policy_seconds}
      scaling_adjustment: -1

  lb_connection_rate_high:
    type: OS::Ceilometer::Alarm
    properties:
      meter_name: network.services.lb.total.connections.rate
      statistic: avg
      period: 60
      evaluation_periods: 3
      threshold: 2
      alarm_actions:
        - {get_attr: [scaleup_policy, alarm_url]}
      comparison_operator: gt

  lb_connection_rate_lo:
    type: OS::Ceilometer::Alarm
    properties:
      meter_name: network.services.lb.total.connections.rate
      statistic: avg
      period: 60
      evaluation_periods: 3
      threshold: 2
      alarm_actions:
        - {get_attr: [scaledown_policy, alarm_url]}
      comparison_operator: lt
