heat_template_version: 2013-05-23
parameters:
  key_name:
    type: string
    default: vagrant
  node_name:
    type: string
    default: stacknode
  node_server_flavor:
    type: string
    default: m1.tiny
  node_image_name:
    type: string
    default: cirros-0.3.4-x86_64-uec
  floating_net_id:
    type: string
    default: dd06fd4d-5538-4b77-a394-9db624a10275
  private_net_id:
    type: string
    default: dd06fd4d-5538-4b77-a394-9db624a10275
  private_subnet_id:
    type: string
    default: 10f5b2eb-2696-460c-acc4-70f7c169efd4

resources:

  vm_port:
    type: OS::Neutron::Port
    properties:
      network_id: { get_param: private_net_id }
      fixed_ips:
        - subnet_id: { get_param: private_subnet_id }

  vm_floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network_id: { get_param: floating_net_id }
      port_id: { get_resource: vm_port }

  vm_instance:
    type: OS::Nova::Server
    properties:
      name: { get_param: node_name }
      image: { get_param: node_image_name }
      flavor: { get_param: node_server_flavor }
      key_name: { get_param: key_name }
      networks:
        - port: { get_resource: vm_port }
