# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"
ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'

# Start config
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.hostname = "devstack2"
  config.vm.box = "ubuntu/trusty64"

  config.vm.network "private_network", ip: "172.16.0.15"
  config.vm.network "private_network", ip: "172.16.0.16"

  config.gui = true
  config.customize ["modifyvm", :id, "--memory", "4096"]
  config.customize ["modifyvm", :id, "--cpus", "2"]
  config.customize ["modifyvm", :id, "--nicpromisc3", "allow-all"]

  config.vm.provision "shell", privileged: false, inline: <<-SHELL

    #!/usr/bin/env bash

    # Set verbose and set exit on error
    set -v
    set -e

    # Create users, set passwords
    sudo useradd -d /home/stack -m stack
    sudo sh -c "echo root:stack | chpasswd"
    sudo sh -c "echo stack:stack | chpasswd"
    sudo sh -c "echo vagrant:stack | chpasswd"

    # Update and install pre-reqs
    sudo apt-get update
    sudo apt-get -y upgrade
    sudo apt-get -y install git

    git clone https://git.openstack.org/openstack-dev/devstack
    git clone https://git.openstack.org/openstack/neutron-lbaas

    cd neutron-lbaas/devstack/samples
    cp local.* webserver.sh ~/devstack
    cd ~/devstack
    ./stack.sh

  SHELL


end
